/* Copy of the signed-in pages. No em or en dashes in copy. */
import type { Locale } from '@/lib/i18n';

export const casesCopy = {
  pt: {
    meta: 'Processos',
    title: { secretary: 'Processos', lawyer: 'Meus processos', client: 'Processos' },
    subtitle: {
      staff: 'Clique duas vezes numa célula para editar. Expanda uma linha para ver o andamento.',
      client: 'Acompanhe os processos da sua empresa. Expanda uma linha para ver o andamento.',
    },
    newCase: 'Novo processo',
    newCaseHint: 'O processo fica no seu nome.',
    open: 'Abrir processo',
    filterBy: (label: string) => `Filtrar: ${label}`,
    tabs: { active: 'Em andamento', finished: 'Finalizados', all: 'Todos' },
    tabsAria: 'Filtrar por situação',
    clearFilters: 'Limpar filtros',
    empty: 'Nenhum processo nesta lista.',
    columns: {
      id: '#',
      title: 'Processo',
      area: 'Área',
      status: 'Situação',
      company: 'Empresa',
      lawyer: 'Advogado',
      updated: 'Atualizado em',
      created: 'Aberto em',
    },
    deleteSelected: (count: number) => (count === 1 ? 'Excluir selecionado' : `Excluir ${count} selecionados`),
    deleteManyTitle: (count: number) => (count === 1 ? 'Excluir este processo?' : `Excluir ${count} processos?`),
    deleteBody: 'A exclusão é definitiva. Para guardar o histórico, mude a situação para Arquivado.',
    deleteOneTitle: (id: number) => `Excluir o processo #${id}?`,
    deleteOneBody: (title: string) =>
      `"${title}" será removido de vez. Para guardar o histórico, mude a situação para Arquivado.`,
    panel: {
      history: 'Andamento',
      noDescription: 'Sem descrição registrada.',
      contact: 'Falar com o advogado',
    },
    fields: {
      title: 'Título do processo',
      area: 'Área',
      areaPlaceholder: 'Escolha a área',
      status: 'Situação',
      company: 'Empresa cliente',
      lawyer: 'Advogado responsável',
      lawyerPlaceholder: 'Escolha o advogado',
      description: 'Descrição e andamento',
      descriptionHint: 'Contexto, prazos e próximos passos. A empresa cliente também vê este texto.',
      submit: 'Abrir processo',
    },
    detail: {
      meta: (id: string) => `Processo #${id}`,
      openedOn: (date: string) => `aberto em ${date}`,
      dataTitle: 'Dados do processo',
      historyTitle: 'Andamento',
      noDescription: 'O advogado ainda não registrou uma descrição.',
      lastUpdate: (date: string) => `Última atualização em ${date}.`,
      save: 'Salvar alterações',
      company: 'Empresa cliente',
      legalName: 'Razão social',
      lawyer: 'Advogado responsável',
      name: 'Nome',
      email: 'E-mail',
      phone: 'Telefone',
      sendEmail: 'Enviar e-mail',
      deleteTitle: 'Excluir processo',
      deleteHint: 'Remove o processo de vez. Para guardar o histórico, use a situação Arquivado.',
      deleteConfirm: 'Excluir este processo?',
      deleteBody: (title: string) => `"${title}" será removido de vez.`,
      mailSubject: (id: number, title: string) => `Processo #${id}: ${title}`,
    },
  },
  en: {
    meta: 'Cases',
    title: { secretary: 'Cases', lawyer: 'My cases', client: 'Cases' },
    subtitle: {
      staff: 'Double click a cell to edit it. Expand a row to read the case history.',
      client: "Follow your company's cases. Expand a row to read the case history.",
    },
    newCase: 'New case',
    newCaseHint: 'The case is opened in your name.',
    open: 'Open case',
    filterBy: (label: string) => `Filter: ${label}`,
    tabs: { active: 'Active', finished: 'Finished', all: 'All' },
    tabsAria: 'Filter by status',
    clearFilters: 'Clear filters',
    empty: 'No cases in this list.',
    columns: {
      id: '#',
      title: 'Case',
      area: 'Area',
      status: 'Status',
      company: 'Company',
      lawyer: 'Lawyer',
      updated: 'Updated',
      created: 'Opened',
    },
    deleteSelected: (count: number) => (count === 1 ? 'Delete selected' : `Delete ${count} selected`),
    deleteManyTitle: (count: number) => (count === 1 ? 'Delete this case?' : `Delete ${count} cases?`),
    deleteBody: 'Deleting is permanent. To keep the history, set the status to Archived instead.',
    deleteOneTitle: (id: number) => `Delete case #${id}?`,
    deleteOneBody: (title: string) =>
      `"${title}" will be removed for good. To keep the history, set the status to Archived instead.`,
    panel: {
      history: 'History',
      noDescription: 'No notes yet.',
      contact: 'Email the lawyer',
    },
    fields: {
      title: 'Case title',
      area: 'Practice area',
      areaPlaceholder: 'Choose the area',
      status: 'Status',
      company: 'Client company',
      lawyer: 'Lawyer in charge',
      lawyerPlaceholder: 'Choose the lawyer',
      description: 'Notes and history',
      descriptionHint: 'Context, deadlines and next steps. The client company sees this text too.',
      submit: 'Open case',
    },
    detail: {
      meta: (id: string) => `Case #${id}`,
      openedOn: (date: string) => `opened on ${date}`,
      dataTitle: 'Case details',
      historyTitle: 'History',
      noDescription: 'The lawyer has not added notes yet.',
      lastUpdate: (date: string) => `Last updated on ${date}.`,
      save: 'Save changes',
      company: 'Client company',
      legalName: 'Legal name',
      lawyer: 'Lawyer in charge',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      sendEmail: 'Send email',
      deleteTitle: 'Delete case',
      deleteHint: 'Removes the case for good. To keep the history, use the Archived status.',
      deleteConfirm: 'Delete this case?',
      deleteBody: (title: string) => `"${title}" will be removed for good.`,
      mailSubject: (id: number, title: string) => `Case #${id}: ${title}`,
    },
  },
};

export const companiesCopy = {
  pt: {
    meta: 'Empresas',
    title: 'Empresas clientes',
    subtitleEdit: 'Clique duas vezes numa célula para editar. Abra a empresa para dar acesso às pessoas dela.',
    subtitleRead: 'Contatos das empresas atendidas pelo escritório.',
    newCompany: 'Nova empresa',
    newCompanyHint: 'Depois do cadastro, abra a empresa para convidar as pessoas que vão acompanhar os processos.',
    empty: 'Nenhuma empresa cadastrada.',
    columns: {
      legalName: 'Razão social',
      cnpj: 'CNPJ',
      email: 'E-mail',
      phone: 'Telefone',
      active: 'Em andamento',
      finished: 'Finalizados',
    },
    openCompany: 'Abrir empresa',
    viewCases: 'Ver processos',
    deleteTitle: (name: string) => `Excluir ${name}?`,
    deleteBody: 'Os acessos das pessoas da empresa também são removidos. Empresas com processos não podem ser excluídas.',
    fields: {
      legalName: 'Razão social',
      cnpj: 'CNPJ',
      cnpjHint: 'Numérico ou alfanumérico.',
      phone: 'Telefone',
      email: 'E-mail de contato',
      submit: 'Cadastrar empresa',
    },
    detail: {
      subtitle: (cnpj: string, active: number, finished: number) =>
        `CNPJ ${cnpj} · ${active} em andamento · ${finished} finalizados`,
      viewCases: 'Ver processos',
      newCase: 'Novo processo',
      registration: 'Cadastro',
      save: 'Salvar alterações',
      email: 'E-mail',
      phone: 'Telefone',
      access: 'Acessos do cliente',
      accessHint: 'Pessoas da empresa que acompanham os processos. Elas só leem.',
      noAccess: 'Ninguém da empresa tem acesso ainda.',
      active: 'Acesso ativo',
      pending: 'Convite pendente',
      resend: 'Reenviar convite',
      remove: 'Remover acesso',
      removeTitle: (name: string) => `Remover o acesso de ${name}?`,
      removeConfirm: 'Remover',
      invite: 'Convidar pessoa',
      inviteName: 'Nome',
      inviteEmail: 'E-mail',
      inviteEmailHint: 'Recebe um link para criar a senha.',
      invitePhone: 'Telefone',
      inviteSubmit: 'Enviar convite',
      invitePending: 'Enviando…',
      deleteTitle: 'Excluir empresa',
      deleteHint: 'Só é possível excluir empresas sem processos. Os acessos das pessoas da empresa saem junto.',
      deleteConfirm: (name: string) => `Excluir ${name}?`,
    },
  },
  en: {
    meta: 'Companies',
    title: 'Client companies',
    subtitleEdit: 'Double click a cell to edit it. Open a company to give its people access.',
    subtitleRead: 'Contacts of the companies the office works for.',
    newCompany: 'New company',
    newCompanyHint: 'After adding it, open the company to invite the people who will follow its cases.',
    empty: 'No companies yet.',
    columns: {
      legalName: 'Legal name',
      cnpj: 'CNPJ',
      email: 'Email',
      phone: 'Phone',
      active: 'Active',
      finished: 'Finished',
    },
    openCompany: 'Open company',
    viewCases: 'View cases',
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteBody: "Its people's access goes too. Companies with cases cannot be deleted.",
    fields: {
      legalName: 'Legal name',
      cnpj: 'CNPJ (Brazilian company number)',
      cnpjHint: 'Numeric or alphanumeric.',
      phone: 'Phone',
      email: 'Contact email',
      submit: 'Add company',
    },
    detail: {
      subtitle: (cnpj: string, active: number, finished: number) =>
        `CNPJ ${cnpj} · ${active} active · ${finished} finished`,
      viewCases: 'View cases',
      newCase: 'New case',
      registration: 'Company details',
      save: 'Save changes',
      email: 'Email',
      phone: 'Phone',
      access: 'Client access',
      accessHint: "People at the company who follow its cases. They can only read.",
      noAccess: 'Nobody at the company has access yet.',
      active: 'Active access',
      pending: 'Invite pending',
      resend: 'Resend invite',
      remove: 'Remove access',
      removeTitle: (name: string) => `Remove ${name}'s access?`,
      removeConfirm: 'Remove',
      invite: 'Invite someone',
      inviteName: 'Name',
      inviteEmail: 'Email',
      inviteEmailHint: 'Gets a link to set a password.',
      invitePhone: 'Phone',
      inviteSubmit: 'Send invite',
      invitePending: 'Sending…',
      deleteTitle: 'Delete company',
      deleteHint: "Only companies without cases can be deleted. Its people's access goes too.",
      deleteConfirm: (name: string) => `Delete ${name}?`,
    },
  },
};

export const lawyersCopy = {
  pt: {
    meta: 'Advogados',
    title: 'Advogados',
    subtitle: 'Clique duas vezes numa célula para editar. Cada advogado vê só os processos em seu nome.',
    newLawyer: 'Novo advogado',
    newLawyerHint: 'A pessoa recebe um convite por e-mail e cria a própria senha.',
    empty: 'Nenhum advogado cadastrado.',
    columns: { name: 'Nome', oab: 'OAB', email: 'E-mail', phone: 'Telefone', access: 'Acesso', active: 'Em andamento' },
    access: { active: 'Ativo', pending: 'Convite pendente', inactive: 'Inativo' },
    viewCases: 'Ver processos',
    resend: 'Reenviar convite',
    deactivate: 'Desativar acesso',
    reactivate: 'Reativar acesso',
    deactivateTitle: (name: string) => `Desativar o acesso de ${name}?`,
    reactivateTitle: (name: string) => `Reativar o acesso de ${name}?`,
    deactivateBody: 'A pessoa sai de todas as sessões e não entra mais. Os processos continuam no histórico.',
    reactivateBody: 'A pessoa volta a entrar com a senha que já tinha.',
    deactivateConfirm: 'Desativar',
    reactivateConfirm: 'Reativar',
    fields: {
      name: 'Nome completo',
      email: 'E-mail',
      oab: 'Inscrição na OAB',
      phone: 'Telefone',
      submit: 'Cadastrar e enviar convite',
    },
  },
  en: {
    meta: 'Lawyers',
    title: 'Lawyers',
    subtitle: 'Double click a cell to edit it. Each lawyer sees only the cases in their name.',
    newLawyer: 'New lawyer',
    newLawyerHint: 'They get an email invite and set their own password.',
    empty: 'No lawyers yet.',
    columns: { name: 'Name', oab: 'OAB (bar number)', email: 'Email', phone: 'Phone', access: 'Access', active: 'Active cases' },
    access: { active: 'Active', pending: 'Invite pending', inactive: 'Inactive' },
    viewCases: 'View cases',
    resend: 'Resend invite',
    deactivate: 'Revoke access',
    reactivate: 'Restore access',
    deactivateTitle: (name: string) => `Revoke ${name}'s access?`,
    reactivateTitle: (name: string) => `Restore ${name}'s access?`,
    deactivateBody: 'They are signed out everywhere and cannot sign in again. Their cases stay in the history.',
    reactivateBody: 'They can sign in again with the password they had.',
    deactivateConfirm: 'Revoke',
    reactivateConfirm: 'Restore',
    fields: {
      name: 'Full name',
      email: 'Email',
      oab: 'OAB number (Brazilian bar)',
      phone: 'Phone',
      submit: 'Add and send invite',
    },
  },
};

export const accountCopy = {
  pt: {
    meta: 'Minha conta',
    title: 'Minha conta',
    subtitle: 'Seus dados de acesso ao Case Desk.',
    demoNotice: 'Você está numa conta de demonstração, compartilhada com outros visitantes: nome e senha ficam bloqueados.',
    name: 'Nome',
    phone: 'Telefone',
    oab: 'OAB',
    edit: 'Editar',
    editing: 'Editando',
    editField: (label: string) => `Editar ${label}`,
    save: 'Atualizar dados',
    emailHint: 'Para trocar o e-mail ou a OAB, fale com a secretaria do escritório.',
    passwordTitle: 'Alterar senha',
    passwordHint: 'Ao trocar a senha, as sessões nos outros dispositivos são encerradas.',
    passwordDemo: 'Indisponível na conta de demonstração.',
    current: 'Senha atual',
    next: 'Nova senha (mínimo de 8 caracteres)',
    repeat: 'Repita a nova senha',
    change: 'Trocar senha',
    showPassword: 'Mostrar senha',
    hidePassword: 'Esconder senha',
  },
  en: {
    meta: 'My account',
    title: 'My account',
    subtitle: 'Your Case Desk sign in details.',
    demoNotice: 'This is a demo account shared with other visitors, so the name and password are locked.',
    name: 'Name',
    phone: 'Phone',
    oab: 'OAB',
    edit: 'Edit',
    editing: 'Editing',
    editField: (label: string) => `Edit ${label}`,
    save: 'Update profile',
    emailHint: 'To change your email or OAB number, ask the office secretary.',
    passwordTitle: 'Change password',
    passwordHint: 'Changing the password signs out your other devices.',
    passwordDemo: 'Not available on the demo account.',
    current: 'Current password',
    next: 'New password (at least 8 characters)',
    repeat: 'Repeat the new password',
    change: 'Change password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
  },
} satisfies Record<Locale, unknown>;
